env:
  browser: true
  commonjs: true
  es2021: true
  jasmine: true
  node: true
plugins: ["wdio"]
extends: 'plugin:wdio/recommended'
parserOptions:
  ecmaVersion: 2021
globals:
  jQuery: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly
  ui5: readonly
  nonUi5: readonly
  common: readonly
  util: readonly
  service: readonly
rules:
  keyword-spacing: 2
  indent: [2, 2, {ignoreComments: true, SwitchCase: 1}]
  no-console: 1
  no-const-assign: 2
  no-extra-semi: 2
  no-irregular-whitespace: 2
  no-redeclare: 2
  no-undef: 2
  no-unused-expressions: 2
  no-return-await: 2
  quotes: [2, 'double', {avoidEscape: true, allowTemplateLiterals: true}]
  prefer-const: 1
  semi: [2, 'always']
