site_name: Qmate Service
site_author: I503232
nav:
  - About: index.md
  - ☰ Reuse API: doc.md
  - Getting Started:
    - Setup: gettingStarted/setup.md
    - Selectors: gettingStarted/selectors.md
  - Best Practices:
    - Authentication: bestPractices/authentication.md
  - Support: 
    - Issues & Feature Requests: IssuesAndFeatureRequests/bugReporting.md
    - Troubleshooting: IssuesAndFeatureRequests/troubleshooting.md
    - Known Issues & Limitations: IssuesAndFeatureRequests/knownIssuesAndLimitations.md
  - Contact: contact.md
theme:
  name: 'material'
  features:
    - content.code.annotate 
    - content.tabs.link
    - navigation.top
  palette:
    - scheme: qmate-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - style/custom.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
docs_dir: docs
site_dir: docs-gen
repo_url: https://github.com/SAP/wdio-qmate-service
site_url: https://sap.github.io/wdio-qmate-service
edit_uri: edit/main/documentation/
copyright: © Copyright 2022, SAP SE & Qmate Service Contributors